### PR TITLE
Make "origin" address symbolic in `symbolic` mode + simplify printed expression

### LINKED ISSUE #857: Unexpected symbolic expression for `balance` for `origin` address
Consider the following minimal contract:

```solidity
pragma solidity ^0.8.30;

contract OnePureFunction {
    function foo() external payable {}
}
```

Save it in `OnePureFunction.sol`. Then, run the command:

```
hevm symbolic --code $(solc --bin-runtime ./OnePureFunction.sol | tail -n1) --show-reachable-tree --sig "foo()" --initial-storage Abstract
```

Output:
```
Using assertion code(s): 1

QED: No reachable property violations discovered

=== Potentially Reachable Expression ===

(Success
  Data:
    (ConcreteBuf "")
  
  State:
    (SymAddr "entrypoint"):
      (Contract
        code:
          (RuntimeCode 608060405260043610601b575f3560e01c8063c298557814601f575b5f5ffd5b60256027565b005b56fea2646970667358221220cd2f5e15115f5aa8f5429d34a31b409b9eb84f187a93b3832170ec5c554e953464736f6c634300081e0033)
        storage:
          (AbstractStore (SymAddr "entrypoint") Nothing)
        tStorage:
          (ConcreteStore <empty>)
        balance:
          (Add
            TxValue
            (Balance
              (SymAddr "entrypoint")
            )
          )
        nonce:
          0x0
      )
    
    (SymAddr "origin"):
      (Contract
        code:
          (RuntimeCode )
        storage:
          (ConcreteStore <empty>)
        tStorage:
          (ConcreteStore <empty>)
        balance:
          (Sub
            0
            TxValue
          )
        nonce:
          0x1
      )
    
  Assertions:
    (PNeg
      (PEq
        (SymAddr "entrypoint")
        (SymAddr "miner")
      )
    )
    (PNeg
      (PEq
        (SymAddr "entrypoint")
        (SymAddr "origin")
      )
    )
    (PNeg
      (PEq
        (SymAddr "miner")
        (SymAddr "origin")
      )
    )
    True
    True
    (PAnd
      (PGEq
        (Max
          4
          (BufLength
            (AbstractBuf "txdata")
          )
        )
        4
      )
      (PLT
        (Max
          4
          (BufLength
            (AbstractBuf "txdata")
          )
        )
        18446744073709551616
      )
    )
)
```

In particular, consider the state of the `origin` address:

```
(SymAddr "origin"):
      (Contract
        code:
          (RuntimeCode )
        storage:
          (ConcreteStore <empty>)
        tStorage:
          (ConcreteStore <empty>)
        balance:
          (Sub
            0
            TxValue
          )
        nonce:
          0x1
      )
```

Why the `balance` is `(Sub 0-TxValue)` and not `(Sub (Balance (SymAddr "origin")) TxValue)`?

### PR DESCRIPTION
**Pull request by msooseth**
## Description
As per https://github.com/argotorg/hevm/issues/857 the `"origin"` is currently fully concrete, and zero. That's not ideal, because we get things like:

```
        balance:
          (Sub
            0
            TxValue
          )
```

For the `"origin"` which actually becomes pretty hilarious when I set `TxValue` to 44 via `--value 44`:
```
    (SymAddr "origin"):
      (Contract
        code:
          (RuntimeCode )
        storage:
          (ConcreteStore <empty>)
        tStorage:
          (ConcreteStore <empty>)
        balance:
          115792089237316195423570985008687907853269984665640564039457584007913129639892
        nonce:
          0x1
      )
```
it rolls around, ooops.

With a symbolic value, it makes a lot more sense::
```
          (Sub
            (Sub
              (Balance
                (SymAddr "origin")
              )
              0
            )
            44
          )
```

Which, with #858 merged, gives:
```
          (Sub
            (Balance
              (SymAddr "origin")
            )
            44
          )
```

Which I think is OK.

We also simplify the expression being printed.

Closes #857 

## Checklist

- [ ] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [x] updated the changelog

### CODE REVIEW

File: cli/cli.hs [hunk 1]
```diff
@@ -764,9 +764,11 @@ symvmFromCommand cExecOpts sOpts cFileOpts calldata = do
                    then InitCode bs mempty
                    else RuntimeCode (ConcreteRuntimeCode bs)
     address = eaddr (.address) (SymAddr "entrypoint")
+    originAddr = eaddr (.origin) (SymAddr "origin")
+    originContr = abstractContract (RuntimeCode (ConcreteRuntimeCode "")) originAddr
```
Comment (blishko) [inline cli/cli.hs]: Why should `RuntimeCode` be `ConcreteRuntimeCode ""`? Seems weird to me.
Shouldn't this be "abstract" somehow?

Comment (msooseth) [reply cli/cli.hs]: Good point. Done! I am now also simplifying the printed expression, so we don't have things like:

```
        balance:
          (Sub
            (Sub
              (Balance
                (SymAddr "origin")
              )
              0
            )
            TxValue
          )
```

But instead, we have:

```
        balance:
          (Sub
            (Balance
              (SymAddr "origin")
            )
            TxValue
          )
```

Which I think makes sense :) This simplification was part of the original idea for the PR, but somehow it got missed. I added it back in.

Let me know what you think!

**Review by blishko — APPROVED** [review]
LGTM!
