### PR TITLE
Do not create duplicate assertions about concrete Keccak values

### LINKED ISSUE #728: Some large queries contained a very large number of repeated lines?
Some large smt2 queries that are produced in the exploration process (that eventually produce an OOM crash) contain a very large amout of repeated lines. The repeated lines looks like this:

```
(assert (= (_ bv54964480676001348254574734048041168120397650765742279736780959122227075130594 256) (keccak (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store (store ((as const Buf) #b00000000) (_ bv12 256) (_ bv238 8)) (_ bv13 256) (_ bv53 8)) (_ bv14 256) (_ bv33 8)) (_ bv15 256) (_ bv28 8)) (_ bv16 256) (_ bv77 8)) (_ bv17 256) (_ bv145 8)) (_ bv18 256) (_ bv38 8)) (_ bv19 256) (_ bv213 8)) (_ bv20 256) (_ bv32 8)) (_ bv21 256) (_ bv187 8)) (_ bv22 256) (_ bv254 8)) (_ bv23 256) (_ bv175 8)) (_ bv24 256) (_ bv60 8)) (_ bv25 256) (_ bv254 8)) (_ bv26 256) (_ bv229 8)) (_ bv27 256) (_ bv254 8)) (_ bv28 256) (_ bv123 8)) (_ bv29 256) (_ bv134 8)) (_ bv30 256) (_ bv242 8)) (_ bv31 256) (_ bv33 8)) (_ bv44 256) (_ bv124 8)) (_ bv45 256) (_ bv39 8)) (_ bv46 256) (_ bv109 8)) (_ bv47 256) (_ bv202 8)) (_ bv48 256) (_ bv171 8)) (_ bv49 256) (_ bv153 8)) (_ bv50 256) (_ bv189 8)) (_ bv51 256) (_ bv22 8)) (_ bv52 256) (_ bv22 8)) (_ bv53 256) (_ bv60 8)) (_ bv54 256) (_ bv27 8)) (_ bv55 256) (_ bv204 8)) (_ bv56 256) (_ bv230 8)) (_ bv57 256) (_ bv113 8)) (_ bv58 256) (_ bv202 8)) (_ bv59 256) (_ bv214 8)) (_ bv60 256) (_ bv161 8)) (_ bv61 256) (_ bv236 8)) (_ bv62 256) (_ bv9 8)) (_ bv63 256) (_ bv69 8)) (_ bv76 256) (_ bv73 8)) (_ bv77 256) (_ bv41 8)) (_ bv78 256) (_ bv52 8)) (_ bv79 256) (_ bv48 8)) (_ bv80 256) (_ bv142 8)) (_ bv81 256) (_ bv152 8)) (_ bv82 256) (_ bv181 8)) (_ bv83 256) (_ bv144 8)) (_ bv84 256) (_ bv166 8)) (_ bv85 256) (_ bv38 8)) (_ bv86 256) (_ bv102 8)) (_ bv87 256) (_ bv107 8)) (_ bv88 256) (_ bv112 8)) (_ bv89 256) (_ bv58 8)) (_ bv90 256) (_ bv109 8)) (_ bv91 256) (_ bv223 8)) (_ bv92 256) (_ bv33 8)) (_ bv93 256) (_ bv32 8)) (_ bv94 256) (_ bv232 8)) (_ bv95 256) (_ bv94 8)) (_ bv108 256) (_ bv10 8)) (_ bv109 256) (_ bv100 8)) (_ bv110 256) (_ bv223 8)) (_ bv111 256) (_ bv148 8)) (_ bv112 256) (_ bv188 8)) (_ bv113 256) (_ bv14 8)) (_ bv114 256) (_ bv3 8)) (_ bv115 256) (_ bv148 8)) (_ bv116 256) (_ bv116 8)) (_ bv117 256) (_ bv219 8)) (_ bv118 256) (_ bv66 8)) (_ bv119 256) (_ bv187 8)) (_ bv120 256) (_ bv82 8)) (_ bv121 256) (_ bv254 8)) (_ bv122 256) (_ bv202 8)) (_ bv123 256) (_ bv12 8)) (_ bv124 256) (_ bv29 8)) (_ bv125 256) (_ bv84 8)) (_ bv126 256) (_ bv4 8)) (_ bv127 256) (_ bv2 8)) (_ bv158 256) (_ bv3 8)) (_ bv159 256) (_ bv245 8)) (_ bv160 256))))
```

This particular line is repeated `15934` times in the file 😱 

You can take a look to the file, it is heavily compressed: [query-1.smt2.zip](https://github.com/user-attachments/files/20013345/query-1.smt2.zip)

### PR DESCRIPTION
**Pull request by blishko**
## Description
Previously we were collecting all equalities of concrete Keccak values into lists. This meant that if an expression (Keccak (ConcreteBuf _)) was present multiple times in the given props, we would add the same assertion multiple times (once per every occurence).

Now we collect the equalities into a set, so no duplicates should occur here anymore.

Fixes #728.

## Checklist

- [x] tested locally
- [x] added automated tests
- [ ] updated the docs
- [x] updated the changelog

### CODE REVIEW

File: test/test.hs [hunk 1]
```diff
@@ -4420,6 +4422,14 @@ tests = testGroup "hevm"
           _ -> liftIO $ assertFailure "Must be satisfiable!"
         let value = subModel cex (Var "a")
         assertEqualM "Can get value out of model in the presence of large buffer!" value (Right $ Lit 0x1)
+    , test "no-duplicates-with-concrete-keccak" $ do
```
Comment (blishko) [inline test/test.hs:4425]: This would fail before.
