### PR TITLE
Test: Fix parsing of contracts in ethereum-tests

### LINKED ISSUE #907: Ethereum tests are not working due to JSON parsing error
With this diff:
```diff
diff --git a/test/EVM/Test/BlockchainTests.hs b/test/EVM/Test/BlockchainTests.hs
index 52f86d07..97b20bbf 100644
--- a/test/EVM/Test/BlockchainTests.hs
+++ b/test/EVM/Test/BlockchainTests.hs
@@ -102,9 +102,14 @@ testsFromFile fname problematicTests = do
   let parsed = parseBCSuite fContents
   liftIO $ putStrLn $ "Parsed " <> fname
   case parsed of
-    Left "No cases to check." -> pure []
-    Left _err -> pure []
-    Right allTests -> mapM runTest $ Map.toList allTests
+    Left "No cases to check." -> do
+      liftIO $ putStrLn $ "No cases to check in " <> fname
+      pure []
+    Left _err -> do
+      liftIO $ putStrLn $ "Error parsing " <> fname <> ": " <> _err
+      pure []
+    Right allTests -> do
+      mapM runTest $ Map.toList allTests
   where
     runTest :: (String, Case) -> m TestTree
     runTest (name, x) = do
```

It becomes evident that we have a `Contract`  parsing error in the JSON, in particular:

```haskell
   , codehash    :: Expr EWord
   , opIxMap     :: VS.Vector Int -- ^ map from byte index to op index
   , codeOps     :: V.Vector (Int, Op)
  , external    :: Bool -- ^ is this an externally owned account? ERROR
   }
   deriving (Show, Eq, Ord)
```

The `external` here is an hevm-internal thing, but it's attempted to be parsed in, and it fails:
```
Reading /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/01_tloadBeginningTxn.json
Parsed /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/01_tloadBeginningTxn.json
Error parsing /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/01_tloadBeginningTxn.json: Error in $['01_tloadBeginningTxn_d0g0v0_Cancun']['0xa00000000000000000000000000000000000000a']: key "external" not found
Reading /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/02_tloadAfterTstore.json
Parsed /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/02_tloadAfterTstore.json
Error parsing /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/02_tloadAfterTstore.json: Error in $['02_tloadAfterTstore_d0g0v0_Cancun']['0xa00000000000000000000000000000000000000a']: key "external" not found
Reading /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/03_tloadAfterStoreIs0.json
Parsed /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/03_tloadAfterStoreIs0.json
Error parsing /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/03_tloadAfterStoreIs0.json: Error in $['03_tloadAfterStoreIs0_d0g0v0_Cancun']['0xa00000000000000000000000000000000000000a']: key "external" not found
Reading /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/04_tloadAfterCall.json
Parsed /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/04_tloadAfterCall.json
Error parsing /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/04_tloadAfterCall.json: Error in $['04_tloadAfterCall_d0g0v0_Cancun']['0xa00000000000000000000000000000000000000a']: key "external" not found
Reading /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/05_tloadReentrancy.json
Parsed /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/05_tloadReentrancy.json
Error parsing /nix/store/v4fmfsh22rh54ykcqzd4dvjafh70l1fc-source/BlockchainTests/GeneralStateTests/Cancun/stEIP1153-transientStorage/05_tloadReentrancy.json: Error in $['05_tloadReentrancy_d0g0v0_Cancun']['0xa00000000000000000000000000000000000000a']: key "external" not found
[...]
```

Hence, currently all `ethereum-tests` fail. This should be easy to fix via a custom parser for the JSON.

Thanks to @blishko for finding this serious bug :S

### PR DESCRIPTION
**Pull request by blishko**
## Description
Due to the changes in RPC cache, parsing of contracts in blockchain
tests was failing.
The solution here is to use a dedicated type, `RPCContract` for
serializing and deserializing contracts.
To fix the blockchain tests, we bring back the JSON parsing code that
was used there before.

As a next step, we could refactor also how contracts are handled in
these tests.

Fixes #907.

## Checklist

- [x] tested locally
- [ ] added automated tests
- [ ] updated the docs
- [ ] updated the changelog

### CODE REVIEW

File: cli/cli.hs [hunk 1]
```diff
@@ -761,7 +760,7 @@ symvmFromCommand cExecOpts sOpts cFileOpts sess calldata = do
           putStrLn "Error, contract not found."
           exitFailure
         Just contract' -> case codeWrapped of
```
Comment (msooseth) [inline cli/cli.hs]: shouldn't this be renamed `rpcContract'` for cosistency?

File: src/EVM/Fetch.hs [hunk 2]
```diff
@@ -150,11 +126,15 @@ data BlockNumber = Latest | BlockNumber W256
 deriving instance Show (RpcQuery a)
 
 data RPCContract = RPCContract
-  { mcCode    :: BS.ByteString
-  , mcNonce   :: W64
-  , mcBalance :: W256
+  { code    :: ByteStringS
+  , nonce   :: W64
+  , balance :: W256
```
Comment (msooseth) [inline src/EVM/Fetch.hs:131]: Thanks!

File: test/contracts/fail/rpc-cache-10307563.json
Comment (msooseth) [inline test/contracts/fail/rpc-cache-10307563.json:1]: Shouldn't there be a cache JSON so it can be loaded for the test?

Comment (gustavo-grieco) [reply test/contracts/fail/rpc-cache-10307563.json:1]: I think @msooseth is correct, this file only needs a small modification and it should work.

Comment (blishko) [reply test/contracts/fail/rpc-cache-10307563.json:1]: The file is not being removed. Only `external` fields are removed.

**Comment by blishko** [comment]
> My only concern is the cache JSON being removed. Now we don't check the JSON cache? Maybe it'd need a separate PR? What do you think? Otherwise, this is great, thanks!

I think GitHub's UI is giving you a false impression.
Only two lines are being deleted from the cache file.

File: cli/cli.hs (hunk 1 above)
Comment (blishko) [reply cli/cli.hs]: Renamed! Thanks!

**Review by msooseth — APPROVED** [review]
OK, tested and it works as expected! Thanks!
